### ISSUE TITLE
Error running Format check on push example

### ISSUE THREAD

**Issue by bourbongoat** [xt0rted/dotnet-format#91]
Not sure if I did something wrong implementing the example yaml or this is a legit bug. 

Run xt0rted/dotnet-format@v1.0.1
  with:
    repo-token: ***
    action: check
    fail-fast: true
/usr/bin/dotnet format --check --dry-run
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-format does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
(node:2919) UnhandledPromiseRejectionWarning: Error: Formatting issues found
    at Object.<anonymous> (/home/runner/work/_actions/xt0rted/dotnet-format/v1.0.1/dist/index.js:1355:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/xt0rted/dotnet-format/v1.0.1/dist/index.js:1335:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:2919) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2919) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
##[error]Formatting issues found

**Comment by anthony-steele-cko** [comment]
You might be running into same as this: https://github.com/xt0rted/dotnet-format/issues/89
